solr_assocs:
  url: "https://solr.monarchinitiative.org/solr/golr"
  timeout: 5
amigo_solr_assocs:
  url: "http://golr.berkeleybop.org"
  timeout: 4
solr_search:
  url: "https://solr.monarchinitiative.org/solr/search"
  timeout: 2
amigo_solr_search:
  url: "http://golr.berkeleybop.org"
  timeout: 2
sparql:
  url: "http://sparql.hegroup.org/sparql"
  timeout: 2
scigraph_ontology:
  url: "https://scigraph-ontology.monarchinitiative.org/scigraph/"
  timeout: 2
scigraph_data:
  url: "https://scigraph-data.monarchinitiative.org/scigraph/"
  timeout: 2
alliance_neo4j:
  url: "bolt://localhost:7687"
  username: neo4j
  password: demo
use_amigo_for:
  - function
ontologies:
  - id: go
    handle: go
    pre_load: true
  - id: hp
    handle: hp
    pre_load: true
  - id: mp
    handle: mp
    pre_load: true
  - id: uberon
    handle: uberon
    pre_load: true
  - id: monarch
    handle: data/monarch.json
    pre_load: true
instances:
  - id: Monarch
    current: false
  - id: Planteome
    current: false
  - id: Gene Ontology
    current: false
  - id: Alliance
    enabled_namespace:
      - biolink.api.bio.endpoints.bioentity
      - biolink.api.graph.endpoints.node
    current: true
